/**
 * Generates packages/cli/src/viewer/assets.generated.ts from the built
 * frontend shell (packages/viewer/dist-static/).
 *
 * Called automatically by scripts/build.ts and by `bun run build:viewer`,
 * so any shell rebuild refreshes the manifest the server embeds/serves.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dir, '../../..')
const staticShellDir = path.join(repoRoot, 'packages', 'viewer', 'dist-static')
const manifestFile = path.join(repoRoot, 'packages', 'cli', 'src', 'viewer', 'assets.generated.ts')

function collectAssets(dir: string, base = ''): Record<string, string> {
  const out: Record<string, string> = {}
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name
    const abs = path.join(dir, entry.name)
    if (entry.isDirectory()) Object.assign(out, collectAssets(abs, rel))
    else out[rel] = readFileSync(abs, 'utf8')
  }
  return out
}

export function generateManifest(): void {
  const assets = collectAssets(staticShellDir)
  const manifest =
    `// AUTO-GENERATED by scripts/gen-manifest.ts — do not edit manually.\n` +
    `export const ASSETS: Record<string, string> = ${JSON.stringify(assets)}\n`
  writeFileSync(manifestFile, manifest)
}

if (import.meta.main) {
  generateManifest()
  console.log(`✓ asset manifest refreshed (${Object.keys(collectAssets(staticShellDir)).length} assets)`)
}
